name: 'test environment'
on:
  push:
  pull_request_target:
  
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      USER_LIST: ${{secrets.APPROVED_USERS}}
    steps:
     - name: UserOK
       if: "contains( $USER_LIST, ${{github.actor}})"
       run: echo "ok"
     - name: BadUser
       if: "!contains( $USER_LIST, ${{github.actor}})"
       run: echo "stop"
