name: 'test environment'
on:
  push:
  pull_request_target:
  
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
     - name: UserOK
       if: "contains( ${{secrets.APPROVED_USERS}}, ${{github.actor}})"
       run: echo "ok"
     - name: BadUser
       if: "!contains( ${{secrets.APPROVED_USERS}}, ${{github.actor}})"
       run: echo "stop"
