name: 'test environment'
on:
  push:
  pull_request_target:
  
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      USER_LIST: ${{secrets.APPROVED_USERS}}
      ACTOR: ${{github.actor}}
    steps:
     - name: Actor
       run: |
            echo env.ACTOR
            echo env.USER_LIST
            
     - name: UserOK
       if: contains( env.USER_LIST, env.ACTOR)
       run: echo "ok"
     - name: BadUser
       if: false == contains( env.USER_LIST, env.ACTOR)
       run: echo "stop"
