name: 'test environment'
on:
  push:
  pull_request_target:
  
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      USER_LIST: ${{secrets.APPROVED_USERS}}
      ACTOR: ${{github.actor}}
    steps:
     - name: Actor
       run: echo "$ACTOR"
     - name: Users
       run: echo "$USER_LIST"
     - name: UserOK
       if: ${{contains( $USER_LIST, $ACTOR)}}
       run: echo "ok"
     - name: BadUser
       if: ${{!contains( $USER_LIST, $$ACTOR)}}
       run: echo "stop"
